"""Initial migration

Revision ID: 8eaa6cb96db2
Revises: 
Create Date: 2025-10-21 19:39:24.781308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eaa6cb96db2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_pairs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('front_key', sa.String(), nullable=False),
    sa.Column('back_key', sa.String(), nullable=False),
    sa.Column('id_json', sa.JSON(), nullable=True),
    sa.Column('grade_json', sa.JSON(), nullable=True),
    sa.Column('listing_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_pairs')
    # ### end Alembic commands ###
